title: AI Conference Deadlines # (Maintained by @abhshkdz)
# email: abhshkdz@vt.edu
description: Countdowns to top CV/NLP/ML/Robotics/AI conference deadlines
author: zlp

domain: "paper.5icv.com"
baseurl: ""

twitter_username: xdler
twitter_hashtag: machinelearning
github_username: xdker
github_repo: xdker.github.io

markdown: kramdown
ga_id: UA-36274081-2

include: ['_pages']
